### ISSUE TITLE
Set up MetricManager Interface

### ISSUE THREAD

**Issue by glenscheng** [matthewl121/ACME_Corp_CLI_Interface#14]
Create Metric Manager Interface

EDIT Scrapped THIS Implementation:
![Image](https://github.com/user-attachments/assets/66d91502-8e16-408a-ad53-b3251ce58cf3)

Follow THIS:
Description:

    Define and set up a TypeScript interface named MetricManager to standardize the interaction with different metrics within the application.
    The MetricManager interface should include methods for handling various metric-related operations, providing a unified approach for metric management.

Requirements:

    Define the Interface:
        Create a MetricManager interface in TypeScript that includes the following methods:

Acceptance Criteria:

    The MetricManager interface is defined in TypeScript with the specified methods and their signatures.
    Documentation is provided for each method, detailing its parameters and return types.
    The interface is implemented in the codebase, and integration points are verified.
    The interface is flexible and adaptable for various metrics.

**Comment by jiaccarino** [comment]
Decided to go with an interface instead of a class for Metric Manager. 
The following is the implemented structure:

interface MetricManager {
- addMetric()
- getMetric()
- evaluateAllMetrics()
- clearAllMetrics()
- removeMetric()
}

abstract class BaseMetricManager implements MetricManager {
    protected metrics: { [metricName: string]: number[] } = {};
    // ...

}

: 
:

class RampUpTimeMetric extends BaseMetricManager {
} etc ...
